@url=http://localhost:5000

POST http://localhost:5000/v1/api/comment
Content-Type: application/json

{
    "userId": "656a088a9509b141c4f337bf",
    "blogId": "657488e5079d5c0499bd245c",
    "content": "comment 1.1"
}

###

DELETE http://localhost:5000/v1/api/comment
Content-Type: application/json

{
    "commentId": "667d9f215948e7582ba58d4f",
    "blogId": "6570bc0a43f5cf59036bc7f2"
}

###

GET http://localhost:5000/v1/api/comment?blogId=6570bc0a43f5cf59036bc7f2

###

GET http://localhost:5000/v1/api/comment/657488e5079d5c0499bd245c?blogId=657488e5079d5c0499bd245c

###

POST http://localhost:5000/v1/api/like
Content-Type: application/json

{
    "blogId": "6570bc0a43f5cf59036bc7f2"
}

###

DELETE http://localhost:5000/v1/api/like
Content-Type: application/json

{
    "blogId": "6570bc0a43f5cf59036bc7f2"
}